### ISSUE TITLE
Remove WireGuard branding and logo

### ISSUE THREAD

**Issue by micahmo** [micahmo/WgServerforWindows#48]
The WireGuard team has requested that this application's name and logo be changed to not directly reference WireGuard. This issue will track work against that goal.

Specifically, the following requests have been made.
1. Remove "WireGuard" from the name of this application (including in the repo and wherever it appears in the app). We will use "Wg" instead.
2. Add proper attribution related to the WireGuard registered trademark.

We have _not_ been asked to change the following.
1. Miscellaneous references to "WireGuard" throughout the documentation.

Please comment if any additional issues are introduced as a result of thse changes. Please also comment if you notice any lingering artifacts in the application once this issue is closed (in case I missed anything).

## Tasks
- [x] Change application logo (2ac1dd312a30f41e9bc3a27f6dcf6c4754b0596f)
- [x] Take new screenshots with new logo (61e746f1a79dd4715fa32054028f5120023bfa1b)
- [x] Change repo description
- [x] Change repo name/URL
  - [x] Verify auto-update from older versions redirects
- [x] Change application name in README (214e15967a1dcc3966bdcf2fc05298d1d69b37e2)
- [x] Change solution and folder names within repo (1062298781f4d5da0ba338c7a01c7a0727267f16)
- [x] Change application name in installer and update install scripts (09c00da1462cb752723549096ec72428aabba49a)
  - [x] Installer should clean up old assemblies, desktop and start menu shortcuts (61ef4ec4039cc593690957b7b3fb73ade39ceb9e)
- [x] Change application name in code (1062298781f4d5da0ba338c7a01c7a0727267f16)
  - [x] Verify that workflows still run (fc7c6d31eab05a29a7fe3dc3b9bbf77e3699468e)
  - [x] Verify splash screen, about box (b901275a9397e3d75f17a4f655f2c776a6a09464)
  - [x] Verify cross-process commands work (main app to status, duplicate main apps, etc.)
  - [x] Check behavior of Windows Tasks which refer to exe names; ~provide upgrade path~ not needed since Tasks refer to the CLI, whose name thankfully didn't change (`ws4w.exe`)
- [x] Add registered trademark note to README attribution (a2c93a4ac54070e415ebad8858c9f0cb48261fd1)
- [x] Modify auto-update checker and version info links (b901275a9397e3d75f17a4f655f2c776a6a09464)
- [x] Having already bumped version numbers, update date when actually releasing ([here](https://github.com/micahmo/WgServerforWindows/blob/ce391f418f7645d3f0a3c6f9c293a34a3bf5fee4/WireGuardServerForWindows/VersionInfo2.xml#L6)) (4472ba4122174f6e61f1908a0f2318bf6857193a)

**Comment by micahmo** [comment]
Done in [v2.0.0]( https://github.com/micahmo/WgServerforWindows/releases/tag/v2.0.0).
